name: Build and Deploy mdBook

on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mdBook
        run: apt install cargo && cargo install mdbook

      - name: Build the book
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
