name: Build and Deploy mdBook

on:
  push:
    branches:
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK-VERSION: "0.4.40"
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install mdbook
      
      - name: Build the book
        run: mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
